/**
 * dev-seedUsers
 * 向 dev_users 集合写入演示用户，供开发/测试使用。
 * 使用方法：在微信开发者工具「云函数」面板右键 → 「上传并部署：云端安装依赖」，部署后调用。
 */
const cloud = require('wx-server-sdk')
cloud.init({ env: cloud.DYNAMIC_CURRENT_ENV })
const db = cloud.database()

const DEMO_USERS = [
  {
    nickname: '林晓雨',
    gender: 'female',
    phone: '13800000001',
    age: 26,
    birthday: '1998-03-15',
    zodiac: '兔',
    zodiacSign: '双鱼座',
    riyuan: '甲子',
    mbti: 'INFJ',
    education: '本科',
    school: '北京大学',
    schoolTier: '985',
    occupation: '产品经理',
    jobLevel: '高级',
    company: '字节跳动',
    income: '20万-30万',
    location: '北京市',
    hometown: '杭州市',
    height: 163,
    weight: 50,
    bio: '喜欢看书、旅行，享受慢生活，希望找一个能一起成长的伴侣。',
    hobbies: ['阅读', '旅行', '瑜伽', '摄影'],
    avatar: '',
    photos: [],
    isRealName: true,
    isFaceVerified: false,
    isVip: false,
    status: 'active',
    createdAt: new Date('2025-01-10').toISOString(),
    updatedAt: new Date().toISOString(),
    filterSettings: {},
  },
  {
    nickname: '陈思琪',
    gender: 'female',
    phone: '13800000002',
    age: 24,
    birthday: '2000-07-22',
    zodiac: '龙',
    zodiacSign: '巨蟹座',
    riyuan: '丁亥',
    mbti: 'ENFP',
    education: '硕士及以上',
    school: '复旦大学',
    schoolTier: '985',
    occupation: '设计师',
    jobLevel: '中级',
    company: '网易',
    income: '10万-20万',
    location: '上海市',
    hometown: '苏州市',
    height: 160,
    weight: 48,
    bio: '热爱设计与艺术，相信美好的事物值得被用心对待。',
    hobbies: ['绘画', '音乐', '美食', '电影'],
    avatar: '',
    photos: [],
    isRealName: false,
    isFaceVerified: false,
    isVip: true,
    status: 'active',
    createdAt: new Date('2025-02-14').toISOString(),
    updatedAt: new Date().toISOString(),
    filterSettings: {},
  },
  {
    nickname: '王紫萱',
    gender: 'female',
    phone: '13800000003',
    age: 28,
    birthday: '1996-11-08',
    zodiac: '鼠',
    zodiacSign: '天蝎座',
    riyuan: '庚午',
    mbti: 'INTJ',
    education: '本科',
    school: '浙江大学',
    schoolTier: '985',
    occupation: '律师',
    jobLevel: '高级',
    company: '某知名律所',
    income: '30万-50万',
    location: '杭州市',
    hometown: '宁波市',
    height: 165,
    weight: 52,
    bio: '独立自主，有目标，热爱法律，业余时间喜欢爬山和读历史。',
    hobbies: ['爬山', '历史', '法律', '读书'],
    avatar: '',
    photos: [],
    isRealName: true,
    isFaceVerified: true,
    isVip: false,
    status: 'active',
    createdAt: new Date('2025-03-01').toISOString(),
    updatedAt: new Date().toISOString(),
    filterSettings: {},
  },
  {
    nickname: '赵梦瑶',
    gender: 'female',
    phone: '13800000004',
    age: 25,
    birthday: '1999-05-20',
    zodiac: '兔',
    zodiacSign: '金牛座',
    riyuan: '壬寅',
    mbti: 'ISFJ',
    education: '本科',
    school: '中山大学',
    schoolTier: '985',
    occupation: '护士',
    jobLevel: '中级',
    company: '广州某三甲医院',
    income: '10万-20万',
    location: '广州市',
    hometown: '广州市',
    height: 158,
    weight: 47,
    bio: '温柔体贴，喜欢做饭，希望与你共同经营一个温暖的家。',
    hobbies: ['烹饪', '追剧', '插花', '猫咪'],
    avatar: '',
    photos: [],
    isRealName: true,
    isFaceVerified: false,
    isVip: false,
    status: 'active',
    createdAt: new Date('2025-04-05').toISOString(),
    updatedAt: new Date().toISOString(),
    filterSettings: {},
  },
  {
    nickname: '刘依依',
    gender: 'female',
    phone: '13800000005',
    age: 27,
    birthday: '1997-09-12',
    zodiac: '牛',
    zodiacSign: '处女座',
    riyuan: '癸酉',
    mbti: 'ESTJ',
    education: '硕士及以上',
    school: '上海交通大学',
    schoolTier: '985',
    occupation: '工程师',
    jobLevel: '高级',
    company: '华为',
    income: '20万-30万',
    location: '深圳市',
    hometown: '武汉市',
    height: 162,
    weight: 51,
    bio: '做事认真负责，技术宅一枚，下班会打游戏，也喜欢骑行。',
    hobbies: ['游戏', '骑行', '编程', '科技'],
    avatar: '',
    photos: [],
    isRealName: false,
    isFaceVerified: false,
    isVip: true,
    status: 'active',
    createdAt: new Date('2025-01-20').toISOString(),
    updatedAt: new Date().toISOString(),
    filterSettings: {},
  },
  {
    nickname: '张浩然',
    gender: 'male',
    phone: '13800000006',
    age: 29,
    birthday: '1995-06-18',
    zodiac: '猪',
    zodiacSign: '双子座',
    riyuan: '乙巳',
    mbti: 'ENTP',
    education: '本科',
    school: '武汉大学',
    schoolTier: '985',
    occupation: '创业者',
    jobLevel: '高级',
    company: '某科技初创',
    income: '30万-50万',
    location: '成都市',
    hometown: '重庆市',
    height: 180,
    weight: 72,
    bio: '热爱探索新事物，有自己的创业项目，希望找到志同道合的另一半。',
    hobbies: ['创业', '徒步', '读书', '音乐'],
    avatar: '',
    photos: [],
    isRealName: true,
    isFaceVerified: false,
    isVip: false,
    status: 'active',
    createdAt: new Date('2025-02-28').toISOString(),
    updatedAt: new Date().toISOString(),
    filterSettings: {},
  },
  {
    nickname: '李明轩',
    gender: 'male',
    phone: '13800000007',
    age: 30,
    birthday: '1994-12-03',
    zodiac: '狗',
    zodiacSign: '射手座',
    riyuan: '丙辰',
    mbti: 'ISFP',
    education: '本科',
    school: '南京大学',
    schoolTier: '985',
    occupation: '摄影师',
    jobLevel: '中级',
    company: '自由职业',
    income: '10万-20万',
    location: '南京市',
    hometown: '扬州市',
    height: 176,
    weight: 68,
    bio: '用镜头记录世界，喜欢旅行，希望遇到懂得欣赏美的你。',
    hobbies: ['摄影', '旅行', '电影', '咖啡'],
    avatar: '',
    photos: [],
    isRealName: false,
    isFaceVerified: false,
    isVip: false,
    status: 'active',
    createdAt: new Date('2025-03-15').toISOString(),
    updatedAt: new Date().toISOString(),
    filterSettings: {},
  },
  {
    nickname: '孙宇轩',
    gender: 'male',
    phone: '13800000008',
    age: 26,
    birthday: '1998-04-25',
    zodiac: '虎',
    zodiacSign: '金牛座',
    riyuan: '戊申',
    mbti: 'INFP',
    education: '本科',
    school: '同济大学',
    schoolTier: '211',
    occupation: '建筑师',
    jobLevel: '初级',
    company: '某建筑设计院',
    income: '10万-20万',
    location: '上海市',
    hometown: '苏州市',
    height: 178,
    weight: 65,
    bio: '对建筑和空间充满热情，相信好的设计让生活更美好。',
    hobbies: ['建筑', '设计', '跑步', '音乐'],
    avatar: '',
    photos: [],
    isRealName: true,
    isFaceVerified: false,
    isVip: false,
    status: 'active',
    createdAt: new Date('2025-04-10').toISOString(),
    updatedAt: new Date().toISOString(),
    filterSettings: {},
  },
  {
    nickname: '周嘉怡',
    gender: 'female',
    phone: '13800000009',
    age: 23,
    birthday: '2001-08-14',
    zodiac: '蛇',
    zodiacSign: '狮子座',
    riyuan: '己卯',
    mbti: 'ESFJ',
    education: '本科',
    school: '厦门大学',
    schoolTier: '211',
    occupation: '教师',
    jobLevel: '初级',
    company: '某中学',
    income: '5万-10万',
    location: '厦门市',
    hometown: '福州市',
    height: 161,
    weight: 49,
    bio: '阳光开朗，喜欢与孩子们相处，业余爱好唱歌和烘焙。',
    hobbies: ['唱歌', '烘焙', '旅行', '绘画'],
    avatar: '',
    photos: [],
    isRealName: false,
    isFaceVerified: false,
    isVip: false,
    status: 'active',
    createdAt: new Date('2025-05-01').toISOString(),
    updatedAt: new Date().toISOString(),
    filterSettings: {},
  },
  {
    nickname: '吴晨曦',
    gender: 'female',
    phone: '13800000010',
    age: 31,
    birthday: '1993-01-28',
    zodiac: '鸡',
    zodiacSign: '水瓶座',
    riyuan: '辛丑',
    mbti: 'ENTJ',
    education: '硕士及以上',
    school: '北京师范大学',
    schoolTier: '211',
    occupation: '心理咨询师',
    jobLevel: '高级',
    company: '某心理健康机构',
    income: '10万-20万',
    location: '北京市',
    hometown: '天津市',
    height: 167,
    weight: 54,
    bio: '理解人心，善于倾听，希望遇到一个能互相支持、共同成长的人。',
    hobbies: ['心理', '冥想', '读书', '跑步'],
    avatar: '',
    photos: [],
    isRealName: true,
    isFaceVerified: true,
    isVip: true,
    status: 'active',
    createdAt: new Date('2025-01-05').toISOString(),
    updatedAt: new Date().toISOString(),
    filterSettings: {},
  },
]

const COL = 'dev_users'

exports.main = async (event) => {
  const results = { added: [], skipped: [], failed: [] }

  for (const user of DEMO_USERS) {
    try {
      const existRes = await db.collection(COL).where({ phone: user.phone }).limit(1).get()
      if (existRes.data && existRes.data.length > 0) {
        await db.collection(COL).doc(existRes.data[0]._id).update({
          data: { status: 'active', updatedAt: new Date().toISOString() },
        })
        results.skipped.push(user.nickname)
        continue
      }
      await db.collection(COL).add({ data: user })
      results.added.push(user.nickname)
    } catch (e) {
      results.failed.push({ nickname: user.nickname, error: e.message })
    }
  }

  const countRes = await db.collection(COL).count()

  return {
    code: 'SUCCESS',
    message: `Seed 完成：新增 ${results.added.length} 个，跳过 ${results.skipped.length} 个，失败 ${results.failed.length} 个`,
    data: {
      ...results,
      totalInCollection: countRes.total || 0,
    },
  }
}
